<?
$hero=array("КэссиКейдж" => "CassieCage",
    "ЭрронБлэк" => "ErronBlack",
    "СабЗиро" => "SubZero",
    "Саб-Зиро" => "SubZero",
    "ДжейсонВурхиз" => "JasonVoorhees",
    "Милина" => "Mileena",
    "ДиВора" => "DiVorah",
    "Горо" => "Goro",
    "Шиннок" => "Shinnok",
    "Тремор" => "Tremor",
    "Кенши" => "Kenshi",
    "Китана" => "Kitana",
    "Эрмак" => "Ermac",
    "Чужой" => "Alien",
    "ТакедаТакахаши" => "TakedaTakahashi",
    "ДжонниКейдж" => "JohnnyCage",
    "Триборг" => "Triborg",
    "ФерраиТорр" => "FerraTorr",
    "Рептилия" => "Reptile",
    "ДжэкиБриггс" => "JacquiBriggs",
    "Таня" => "Tanya",
    "КунгДжин" => "KungJin",
    "СоняБлейд" => "SonyaBlade",
    "Скорпион" => "Scorpion",
    "КотальКан" => "KotalKahn",
    "ЛюКенг" => "LiuKang",
    "КуанЧи" => "QuanChi",
    "КунгЛао" => "KungLao",
    "Джакс" => "Jax",
    "Райдэн" => "Raiden",
    "Хищник" => "Predator",
    "Кано" => "Kano",
    "БоРайЧо" => "BoRaiCho",
    "Кожаноелицо" => "Leatherface",
"Ди'Вора"=>"DiVorah");
Echo "ok";
